---
- name: Install repos and dependencies
  yum:
    name:
      - epel-release
      - centos-release-scl
      - http://yum.centreon.com/standard/20.04/el7/stable/noarch/RPMS/centreon-release-20.04-1.el7.centos.noarch.rpm
      - firewalld
      - policycoreutils-python
      - selinux-policy
    state: present

- name: Allow http in firewalld
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - http
  notify: Reload firewalld

- name: Disable SELinux
  selinux:
    state: disabled

- name: Install required packages
  yum:
    name:
      - centreon
      - centreon-database
      - python-pip
      - libselinux-python
  notify: Restart mariadb

- meta: flush_handlers

- name: Install MySQL connector
  pip:
    name: pymysql
