---
- name: Allow http in firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - http
  notify: Reload firewalld

- name: Disable SELinux
  selinux:
    state: disabled
