---
- name: Restart mariadb
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: yes

- name: Restart httpd
  systemd:
    name: httpd24-httpd
    state: started
    enabled: yes

- name: Restart rh-php72-php-fpm
  systemd:
    name: rh-php72-php-fpm
    state: restarted

- name: Restart httpd
  systemd:
    name: httpd24-httpd
    state: started
    enabled: yes

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded
