---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${distribution}:${version}"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
